version: "3.8"
services:
  test_db:
    image: postgres:15.1-alpine
    ports:
      - "${TEST_DB_PORT}:5432"
    expose:
      - "${TEST_DB_PORT}"
    environment:
      - POSTGRES_USER=${TEST_DB_USERNAME}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_DATABASE}
      - TEST_MODE=True
    healthcheck:
      test: [ "CMD", "sh", "-c", "pg_isready -q -d ${TEST_DB_DATABASE} -U ${TEST_DB_USERNAME}" ]
      timeout: 45s
      interval: 1s
      retries: 10
    restart: unless-stopped


  api:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on:
      test_db:
        condition: service_healthy
    environment:
      - DB_HOST=${TEST_DB_HOST}
      - TEST_MODE=True
    command:
      - sh
      - -c
      - "pytest -v"
